# encoding: UTF-8

mysql: &mysql
  adapter: mysql2
  reconnect: true
  pool: 50
  port: 37510
  host: s6-atyun.servers.atyun.com.cn
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

mysql_localhost: &mysql_localhost
  <<: *mysql

weinei_dev_localhost: &weinei_dev_localhost
  <<: *mysql
  database: weinei_dit_20151112
  username: weinei_dit
  password: b9&532q1tcU382TD

development: &development
  <<: *weinei_dev_localhost

test: &test
  <<: *development

  database: weinei_dev_20151208_test_<%=ENV['TEST_ENV_NUMBER']%>
  username: weinei_dev
  password: u%oUAOkLX$TfL52N

production: &production
  <<: *development
